#!/bin/sh
# HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000
export PATH="$HOME/.local/bin":$PATH
export MANPAGER='nvim +Man!'
export MANWIDTH=999
export PATH=$HOME/.cargo/bin:$PATH

# FNM
case "$(uname -s)" in

Darwin)
	export PATH=$HOME/.fnm:$PATH
	;;

Linux)
	export PATH=$HOME/.local/share/fnm:$PATH
	;;

CYGWIN* | MINGW32* | MSYS* | MINGW*)
	;;

*)
	;;
esac

export PATH="$HOME/.local/share/neovim/bin":$PATH
#export PATH="$PATH:./node_modules/.bin"
eval "$(fnm env)"
